config/routes.rb
Rails.application.routes.draw do
  resources :candidates do
    resource :answer
  end
  resources :regions
  resources :elections
  resources :parties do
    resource :answer
  end
  resources :questions do
    resources :options, shallow: true
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #https://hackernoon.com/building-a-simple-session-based-authentication-using-ruby-on-rails-9tah3y4j
  resources :users
  resources :user_sessions, only: %i(new create destroy)
  get '/auth/:provider/callback', to: 'omniauth_callbacks#create', as: :omniauth_callback

  resources :user_recover_passwords, only: %i(new create edit update)
  resources :user_confirmations, only: %i(new create show)
  
  resource :answer
  resources :attachments, only: %i(destroy)
  resource :map, only: %i[show]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show"

  get "/:page", to: "home#show", as: :home
  root 'maps#show'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/controllers/user_recover_passwords_controller.rb
class UserRecoverPasswordsController < ApplicationController

  def new
    @user_recover_password = UserRecoverPassword.new
  end

  def create
    @user_recover_password = UserRecoverPassword.new(recover_params)
    if @user_recover_password.valid?
      @user_recover_password.send_email
      redirect_to new_user_session_path, notice: I18n.translate('user_recover_passwords.send_instructions')
    else
      render action: :new, status: :unprocessable_entity  
    end
  end

  def edit
    @user = User.find params[:id]
    @user_new_password = UserNewPassword.new(@user)
    unless @user.recover_token == params[:token]
      redirect_to new_user_recover_password_path, alert: "El token no coincide. Intenta enviarte una nueva solicitud"
    end
  end

  def update
    @user = User.find params[:id]
    @user_new_password = UserNewPassword.new(@user, password_params)
    if @user.recover_token == params[:token] && @user_new_password.save
      user_log_in @user
      redirect_to @user, notice: "He cambiado tu contraseña e iniciaste sesión. \n Bienvenido de vuelta #{@user}."
    else
      render action: :edit, status: :unprocessable_entity  
    end
  end

  protected
    def recover_params
      params.require(:user_recover_password).permit(:email)
    end

    def password_params
      params.require(:user_new_password).permit(:password, :password_confirmation)
    end

end

app/views/user_recover_passwords/edit.html.slim
.flex.items-center.flex-col

  .max-w-md.w-full

    h2.title = t(".change_your_password")
    = form_with model: @user_new_password, url: user_recover_password_path(@user),
      method: :put, class: "form"  do |f|

      = render "shared/form_errors", object: @user_new_password

      = hidden_field_tag :token, params[:token]

      .input
        = label_tag t(".new_password")
        = f.password_field :password, autofocus: true, required: false,
          autocomplete: "new-password", class: "w-full"
        .text-sm.text-right.mt-1 = "Mínimo 8 caracteres"
      
      .input
        = label_tag t(".confirm_new_password")
        = f.password_field :password_confirmation, autofocus: true, required: false,
          autocomplete: "new-password", class: "w-full"

      .form-actions
        = f.button t(".change_my_password"), class:"btn btn--primary btn--md w-full"

app/views/user_recover_passwords/new.html.slim
h2.title.text-center = t(".forgot_your_password")
.flex.items-center.flex-col

  .max-w-md.w-full

    p.title.py-4 Envía un enlace a tu correo para crear una nueva contraseña

    = form_with model: @user_recover_password, class: "form" do |f|
      = render "shared/form_errors", object: @user_recover_password

      .input
        = f.label :email
        = f.email_field :email,
          autofocus: true, autocomplete:"email",
          required: true, class: "w-full"
      
      .form-actions
          = f.submit t(".send_me_reset_password_instructions"),
          class: "btn btn--primary btn--md w-full"

      .flex.justify-between.my-12
        = link_to new_user_session_path,
          class: "btn block btn--secondary" do
          .flex.items-center
            .= inline_svg_tag "user.svg", class: "inline-block"
            .ml-1= t('.sign_in')

        = link_to new_user_path,
          class: "btn block btn--secondary" do
          .flex.items-center.justify-center
            .= inline_svg_tag "user-plus.svg"
            .ml-1= t(".sign_up")