config/routes.rb
Rails.application.routes.draw do
  resources :candidates do
    resource :answer
  end
  resources :regions
  resources :elections
  resources :parties do
    resource :answer
  end
  resources :questions do
    resources :options, shallow: true
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #https://hackernoon.com/building-a-simple-session-based-authentication-using-ruby-on-rails-9tah3y4j
  resources :users
  resources :user_sessions, only: %i(new create destroy)
  get '/auth/:provider/callback', to: 'omniauth_callbacks#create', as: :omniauth_callback

  resources :user_recover_passwords, only: %i(new create edit update)
  resources :user_confirmations, only: %i(new create show)
  
  resource :answer
  resources :attachments, only: %i(destroy)
  resource :map, only: %i[show]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show"

  get "/:page", to: "home#show", as: :home
  root 'maps#show'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
  validates :name, :value_x, :value_y, presence: true
  
  def to_s
    name
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_question
  before_action :set_option, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[new edit create update destroy]

  # GET /options or /options.json
  def index
    @options = @question.options.all
  end

  # GET /options/1 or /options/1.json
  def show
  end

  # GET /options/new
  def new
    @option = @question.options.new
    authorize(@option)
  end

  # GET /options/1/edit
  def edit
  end

  # POST /options or /options.json
  def create
    @option = @question.options.new(option_params)
    authorize(@option)
    respond_to do |format|
      if @option.save
        format.html { redirect_to question_options_url(@option.question), notice: "Option was successfully created." }
        format.json { render :show, status: :created, location: question_options_url(@option.question) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1 or /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to question_options_url(@option.question), notice: "Option was successfully updated." }
        format.json { render :show, status: :ok, location: question_options_url(@option.question) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1 or /options/1.json
  def destroy
    @option.destroy
    respond_to do |format|
      format.html { redirect_to question_options_url(@option.question), notice: "Option was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find_by(id: params[:question_id])
    end
    
    def set_option
      @option = Option.find(params[:id])
      authorize(@option)
    end

    # Only allow a list of trusted parameters through.
    def option_params
      params.require(:option).permit(:name, :description, :value_x, :value_y)
    end
end

app/views/options/_form.html.slim
= form_with model: [@question, @option], class: "form" do |f|
  = render "shared/form_errors", object: @option

  .field
    = f.label :name
    = f.text_field :name, class: "w-full"
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :value_x
    = f.number_field :value_x
  .field
    = f.label :value_y
    = f.number_field :value_y
  .actions = f.submit class: "btn btn--primary", "data-disable-with" => "Guardando..."

app/views/options/edit.html.slim
h1.title.mb-4 Modificando opción

== render 'form'

app/views/options/index.html.slim
.flex.items-center.mb-8
  h1.title Opciones para #{@question} (#{@question.options.count})
  .ml-auto = new_button [@question, Option]

.overflow-x-auto
  table.table
    thead
      tr
        th Name
        th Description
        th Value x
        th Value y
        th

    tbody
      - @options.each do |option|
        tr
          td = option.name
          td = option.description
          td = option.value_x
          td = option.value_y
          td = edit_buttons option

app/views/options/new.html.slim
h1.title.mb-4 Nueva opción para #{@question}

== render 'form'

app/views/options/show.html.slim
p#notice = notice

p
  strong Question:
  = @option.question
p
  strong Name:
  = @option.name
p
  strong Description:
  = @option.description
p
  strong Value x:
  = @option.value_x
p
  strong Value y:
  = @option.value_y

=> link_to 'Edit', edit_option_path(@option)
'|
=< link_to 'Back', options_path