config/routes.rb
Rails.application.routes.draw do
  resources :candidates do
    resource :answer
  end
  resources :regions
  resources :elections
  resources :parties do
    resource :answer
  end
  resources :questions do
    resources :options, shallow: true
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #https://hackernoon.com/building-a-simple-session-based-authentication-using-ruby-on-rails-9tah3y4j
  resources :users
  resources :user_sessions, only: %i(new create destroy)
  get '/auth/:provider/callback', to: 'omniauth_callbacks#create', as: :omniauth_callback

  resources :user_recover_passwords, only: %i(new create edit update)
  resources :user_confirmations, only: %i(new create show)
  
  resource :answer
  resources :attachments, only: %i(destroy)
  resource :map, only: %i[show]

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show"

  get "/:page", to: "home#show", as: :home
  root 'maps#show'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :answerer, polymorphic: true, optional: true, touch: true
  has_many :answer_lines, dependent: :destroy
  accepts_nested_attributes_for :answer_lines

  def completed?
    pending_count == 0
  end

  def value_x
    answer_lines.sum{ |l| l.value_x || 0 }
  end

  def value_y
    answer_lines.sum{ |l| l.value_y || 0 }
  end

  def answered_count
    AnswerLine.where(answer_id: id).count
  end

  def pending_count
    Question.count - answered_count
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Answereable
  before_action :set_answerer
  before_action :set_answer

  def new
    render :edit
  end

  def show
  end

  def edit
  end

  def create
    update
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        @answer.answerer&.touch
        format.html { redirect_to [@answerer, @answer], notice: "Tus respuestas han sido actualizadas" }
        format.json { render :show, status: :ok, location: @answer }
        format.turbo_stream do
          @question = Question.find params[:question_id]
          render 'update'
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to (@answerer.present? ? [@answerer, :answer] : map_path), notice: "He borrado tus respuestas" }
      format.json { head :no_content }
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer)
        .permit(answer_lines_attributes: [:question_id, :option_id, :id])
    end

    def set_answerer
      @answerer = if params[:candidate_id]
        Candidate.find params[:candidate_id]
      elsif params[:party_id]
        Party.find params[:party_id]
      else
        nil
      end
      authorize(@answerer) if @answerer.present?
    end
end

app/views/answers/_nav.html.slim
.flex.items-center
  .
    - if answer.completed?
      = link_to (answer.answerer || map_path),
        class: "btn btn--primary btn--sm inline-block flex items-center" do
          .mr-1= inline_svg_tag "check-circle.svg"
          = "Ver resultado"
    - else
      . class="btn--terciary btn--sm inline-block flex items-center"
        .sm.mr-2= "#{answer.answered_count}/#{Question.count}"
        meter max="#{Question.count}" value="#{answer.answered_count}"

  - if @answer.answer_lines.any?
    .ml-3
      = button_to (answer.answerer ? [answer.answerer, :answer] : answer_path),
        method: :delete,
        data: { confirm: "Borraré todas las respuestas. ¿Segur@?",
          disable_with: 'borrando...' },
        class: "block btn btn--secondary btn--sm flex items-center" do 
        .mr-1= inline_svg_tag "trash.svg"
        span Borrar

app/views/answers/_question.html.slim
- url = @answerer.present? ? polymorphic_path([@answerer, :answer], question_id: question.id) : answer_path(question_id: question.id)
= form_with model: answer,
  url: url,
  class: "form mb-6" do |f|
  - answer_line = answer.answer_lines.select{ |al| al.question_id == question.id }.first || answer.answer_lines.build(question_id: question.id)
  = f.fields_for :answer_lines, answer_line do |ff|
    .field.border-b-2.border-gray-600.pb-6
      .mb-3
        h3.title.mb-1.flex.items-inline
          = "#{question.id}: "
          = question
          = inline_svg_tag "check_step.svg", width: 24, height: 24, class: "ml-1 text-green-800" if ff.object.option.present?

        .text-lg= simple_format question.description

      - question.options.order(:id).each do |option|
        = ff.label :option_id, value: option.id do 
          = ff.radio_button :option_id, option.id, class: "js-submit-on-click"
          = ff.hidden_field :question_id
          span.text-lg class="#{ff.object.option == option ? "underline" : ""}"
            = option.name

app/views/answers/edit.html.slim
- content_for :meta_title, "Cuestionario de posición política | #{DEFAULT_META["meta_title"]}"
- content_for :meta_description, "Contesta estas #{Question.count} preguntas para decidir mejor"

.mb-4
  h2.title.mb-2 Preguntas
  - if @answerer.present?
    h4.title= @answerer

.mb-4.py-1.flex.items-center.sticky.top-0.p-1.bg-gray-100.shadow.z-10
  = turbo_frame_tag "top_nav", target: "_top", class: "ml-auto" do
    = render "nav", answer: @answer 

p.mb-2
  | Contesta estas #{Question.count} preguntas. 
  | Te tomará aproximadamente 10 minutos. 

p.mb-4.italic
  | Todas tus respuestas son Correctas.  
  | No hay respuestas buenas o malas

- Question.order(:id).all.each do |question|
  = turbo_frame_tag question do 
    = render "question", answer: @answer, question: question

.mb-4.py-1.flex.items-center.sticky.top-0.p-1.bg-gray-100.shadow.z-10
  = turbo_frame_tag "bottom_nav", target: "_top", class: "ml-auto" do
    = render "nav", answer: @answer 

app/views/answers/show.html.slim
- content_for :meta_title, "Ubícate | #{DEFAULT_META["meta_title"]}"
- content_for :meta_description, "Conoce tus coordenadas políticas para decidir mejor"

h1.title.mb-4.flex.items-center Ubícate 

- if @answerer 
  h2.title.mb-4= link_to @answerer, @answerer

p.mb-4 Conoce tus coordenadas políticas para poder decidir mejor. Contesta un breve cuestionario.

.mb-4.flex.item-center
  = link_to @answerer ? [:edit, @answerer, :answer] : edit_answer_path,
    class: "btn btn--primary block flex items-center" do 
    .= inline_svg_tag "clipboard.svg"
    .ml-1 Cuestionario

  .ml-4
    - if @answer.completed?
      = link_to map_path(x: @answer.value_x, y: @answer.value_y),
        class: "block btn bg-green-800 text-white flex items-center" do
          .= inline_svg_tag "map-pin.svg"
          .ml-1= "Ubícate respecto a los Partidos políticos"
    - else
      p.mb-4.text-green-900
        | Contesta el breve cuestionario y podrás conocer tus coordenadas políticas. 

- if @answer.completed?
  = render "maps/graph", x: @answer.value_x * 5, y: @answer.value_y * 5
  p.mb-4.text-center= "Coordenadas X:#{@answer.value_x}, Y:#{@answer.value_y}"

app/views/answers/update.turbo_stream.erb
<%= turbo_stream.update dom_id(@question) do %>
  <%= render "question", question: @question, answer: @answer %>
<% end %>
<%= turbo_stream.update 'top_nav' do %>
  <%= render "nav", answer: @answer %>
<% end %>
<%= turbo_stream.update 'bottom_nav' do %>
  <%= render "nav", answer: @answer %>
<% end %>